### ISSUE TITLE
Get Segfault

### ISSUE THREAD

**Issue by PeratX** [colder/php-weakref#24]

**Comment by PeratX** [comment]
I see you guys have fixed that problem, please release a new version.

**Comment by colder** [comment]
I have just released the latest version which hopefully will fix this issue.

**Comment by PeratX** [comment]
That is great! Thx.

**Comment by commercebyte** [comment]
The segfault issue on PHP7 + Apache2 module is fixed in my fork -
https://github.com/commercebyte/php-weakref

**Comment by colder** [comment]
If you make a pull request, I will happily merge it and release a new version for the fix.

**Comment by commercebyte** [comment]
The pull request is created, thank you -
______________
Jim Zubov
CommerceByte Consulting
President

**Comment by PeratX** [comment]
I am looking forward to it :)
