### ISSUE TITLE
Installation Requirements?

### ISSUE THREAD

**Issue by Haravikk** [colder/php-weakref#29]
So I was excited to see that WeakRef is now available to install for php 7, but it's been so long since I actually installed WeakRef I'm not sure if I'm missing a step.

I installed WeakRef via `pecl` as it seemed the easiest way, and added `extension=weakref.so` in a file under `/etc/php/7.0/fpm/conf.d`, which seemed the neatest place to put it.

When I look in `phpinfo()` I can verify that Weakref is loaded, but the class is not available for use. Are there any additional requirements that I may be missing?

**Comment by colder** [comment]
What do you mean by "class is not available". does it simply say "Class 'Weakref' not found" ?

Are you sure you check phpinfo() under the same conditions in which you try to use weakref ? If the extension is loaded then Weakref should be available.

**Comment by Haravikk** [comment]
Ack, I'm just an idiot; I only loaded the module under fpm but I do a lot of my testing via command line, me being the fool I am viewed PHP info through a browser (fpm) not realising it's the command line setup that was the problem.

Anyway, I've got it loading just fine now, apologies for the waste of time!

**Comment by colder** [comment]
aha! Nice to hear there is no real problem!
